AddonId: KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9
Packages:
  - Version: 2.6.0
    RequiredApiVersion: 2.6
    ReleaseDate: 2025-09-08
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v2.6.0/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_2_6_0.pthm
    Changelog:
      - Changed display of covers in grid view to zoom on hover etc.
      - Added several theme modifier settings to Grid View for performance optimizations.
  - Version: 2.5.1
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-12-07
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v2.5.1/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_2_5_1.pthm
    Changelog:
      - Fixed margin for GOG Second Class Watcher control
  - Version: 2.5.0
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-12-07
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v2.5.0/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_2_5_0.pthm
    Changelog:
      - Added support for the new GOG Second Class Watcher addon.
      - optimized performance in grid view
      - made main window background  darker and shadows of covers more prominent
      - added rounded corners to selected game in grid view
      - fixed top margin for context action button when playing a game
  - Version: 2.4.0
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-11-13
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v2.4.0/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_2_4_0.pthm
    Changelog:
      - Added support for the new WebExplorer addon.
      - Made tabs scroll horizontally instead of wrapping, when they don't fit anymore.
      - Fixed visibility of several details controls. Some were tied to the wrong field couldn't be deactivated correctly because of that.
  - Version: 2.3.1
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-10-22
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v2.3.1/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_2_3_1.pthm
    Changelog:
      - Changed display of link icons back to the old style, in the hope that fixes crashes after importing link metadata.
  - Version: 2.3.0
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-10-22
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v2.3.0/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_2_3_0.pthm
    Changelog:
      - Added additional Metadata Utilities controls for developer, publisher, region and Platform.
      - You can now add and remove values from fields added through Metadata Utilities directly in details view.
      - Changed Completion Status combobox to fix crashes.
      - Completion Status combobox can now also be disabled.
      - Fixed wrong margins for games, that can't be installed.
      - Changed group box border to a more subtle color.
  - Version: 2.2.2
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-10-14
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v2.2.2/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_2_2_2.pthm
    Changelog:
      - Fixed crashes related to slider controls (videos, several settings pages).
      - Fixed top/bottom margin in grid view, when it's not grouped.
      - Hopefully fixed text in time played box, that appeared blurry for some users.
  - Version: 2.2.1
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-10-14
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v2.2.1/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_2_2_1.pthm
    Changelog:
      - Fixed wrong scrollbar color.
      - Changed scrollbars to only appear on mouse over.
      - Reactivated the scrollbar in the details panel.
      - Changed the color of the resize button in the grid view.
  - Version: 2.2.0
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-10-13
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v2.2.0/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_2_2_0.pthm
    Changelog:
      - Added option to display the link bar as an actual box with background.
      - Added option to disable the display of the details section including description completely.
      - Added option to display the time played in the button bar.
      - Remade the slider to resize the covers in grid mode.
      - Added subtle borders to buttons.
      - Fixed Duplicate Hider icons appearing behind the scroll bar.
      - Removed windows aero glass frame again, since it was causing more trouble than the added drop shadows were worth.      
  - Version: 2.1.0
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-10-12
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v2.1.0/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_2_1_0.pthm
    Changelog:
      - Added steam player count (via Steam News Viewer).
      - Added Duplicate Hider buttons to the game details (appear, when hovering over the background image).
      - Removed uneccessary animation from Duplicate Hider items to fit the theme better and for better performance.
      - Performance optimizations
      - Fixed game name offset, when no logo is available and game name is only shown, when there is no logo.
      - Fixed background image of last game is shown, when the selected game has no background.
      - Fixed backgrounds in details mode only working, when BackgroundChanger addon is installed.
      - Fixed more missing drop shadows.
      - Fixed double drop shadow on addon buttons.
  - Version: 2.0.0
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-10-11
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v2.0.0/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_2_0_0.pthm
    Changelog:
      - Added support for Background Changer
      - Added editable completion status and user rating in the details panel (via Theme Extras)
      - Added stars to ratings in details panel (via Theme Extras)
      - Added context menu to Background image to quickly access ExtraMetadata and BackgroundChanger functions. 
      - Fixed missing drop shadows
      - removed option to display links as a box, but added functionality to add your own link icons (via Theme Extras)
  - Version: 1.9.0
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-10-09
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v1.9.0/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_1_9_0.pthm
    Changelog:
      - Added new app logo, that fits the theme.
      - Changed color of group boxes to make them more noticeable.
      - Fixed different alignment of theme's own and metadata utilities controls depending on the set font.
      - Fixed wrong color of separators in settings windows.
  - Version: 1.8.1
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-10-08
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v1.8.1/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_1_8_1.pthm
    Changelog:
      - Fixed covers looking a bit blurry since the last update.
  - Version: 1.8
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-10-08
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v1.8/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_1_8.pthm
    Changelog:
      - Changed red colors to blue. If you want the old color scheme back, simply replace the constants.xaml with the constants-red.xaml in the theme folder.
      - Several changes to group headers and tab buttons in grid and details view. For optimal experience it is now recommended to use "Corbel" as the application font. It's included in Windows.
      - Added subtle drop shadows to all buttons and the covers in grid view
      - Made some bright colors a bit more subtle
  - Version: 1.7
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-10-06
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v1.7/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_1_7.pthm
    Changelog:
      - ATTENTION! To use the theme and display categories, tags etc. it is now mandatory to have the addon Metadata Utilities installed, because the theme replaces some standard controls with the ones from Metadata Utilities.
      - Support to display virtual custom fields via Metadata Utilities and its prefixes feature.
      - Added optional link bar between the game buttons and the details as an alternative to have the links in the details itself.
      - Removed option to show features and tags as a box. May come back later through a setting in Metadata Utilities.
      - Moved the links to the bottom of the details panel.
      - Several small layout optimizations
  - Version: 1.6
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-06-02
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v1.6/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_1_6.pthm
    Changelog:
      - added support for Steam Screenshots addon
      - integrated bottom slider directly into the grid, so the game covers go all the way to the bottom instead of cutting off above the slider.
      - Made background of filter panel transparent to see wallpaper backgrounds behind it.
      - Added banners for sources Humble, Emulation and Origin aka EA app
  - Version: 1.5
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-03-15
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v1.5/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_1_5.pthm
    Changelog:
      - added border to all sides of a control instead of just the bottom and changed the default color to a slightly brighter grey than the background.
      - made background of certein controls (mainly edits) darker
      - removed border from some controls that look better without one
      - reverted top margin change for h2 elements in html view, because it didn't look as intended when not using paragraphs. Added a "no-top-margin" class instead to add to descriptions manually if needed.
  - Version: 1.4
    RequiredApiVersion: 2.6
    ReleaseDate: 2024-03-13
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v1.4/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_1_4.pthm
    Changelog:
      - added support for How Long To Beat progress bar
      - tweaked colors a bit
      - added small gap between details and description panels
      - fixed install button on game covers in grid view not hiding, when option is set.
      - tweaked inconsistent top margins in html view
  - Version: 1.3
    RequiredApiVersion: 2.5
    ReleaseDate: 2023-11-11
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v1.3/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_1_3.pthm
    Changelog:
      - added tab for Play Notes addon
      - normal notes are now shown in a tab together with Play Notes.
      - added tab to show a video via ExtraMetadata addon
      - added tab for SuccessStory addon
      - added tab for ScreenshotsVisualizer addon
      - added tab for GameActivity addon
      - added tab for ReviewViewer addon
      - added tab for NewsViewer addon
      - added tab for CheckDlc addon
      - added tab for Game Relations addon
  - Version: 1.2
    RequiredApiVersion: 2.5
    ReleaseDate: 2023-10-07
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v1.2/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_1_2.pthm
    Changelog:
      - changed banners for Arcade, NES, PC Windows, Sega Genesis (switched to Mega Drive), Riot Games, Origin to EA Desktop, Humble Bundle, GOG
      - moved banners for MSX, MSX2 and PC98 from PlatformName to PlatformSpecId
      - added banners for FM Towns, Flash, Sammy Atomiswave, Amiga, Amiga CD32, Neo Geo and GameJolt
      - changed colors slightly
      - made scrollbar visible when not hovered over
      - added drop shadow to cover in details view
  - Version: 1.1
    RequiredApiVersion: 2.5
    ReleaseDate: 2023-06-12
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v1.1/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_1_1.pthm
    Changelog:
      - Added option to display features, tags and links in a wrap panel instead of a list text to save space.
      - Added option to hide the play/install buttons for manually added games.
      - Removed top margin from paragraphed text in description.
      - Fixed missing game name when no logo is available in details mode.
  - Version: 1.0
    RequiredApiVersion: 2.5
    ReleaseDate: 2023-05-31
    PackageUrl: https://github.com/HerrKnarz/Playnite-Theme-KNARZnite/releases/download/v1.0/KNARZnite_68cee656-e677-42ab-a33e-9d9e6dfbefb9_1_0.pthm
    Changelog:
      - initial release